### ISSUE TITLE
RFC: License

### ISSUE THREAD

**Issue by avivace** [gbdev/gbadoc#3]
Which license should we apply to the produced assets (figures and text)?

**Comment by LunarLambda** [comment]
I see no particular reason not to publish it in the public domain (or any other license that will ensure the information stays freely accessible forever)

**Comment by quentin-dev** [comment]
I agree with @LunarLambda, it could also be nice to have the license guarantee that we're credited as the original authors if the assets are ever forked and whatnot

**Comment by Lokathor** [comment]
CC0 seems simplest for documentation to use.

**Comment by AntonioND** [comment]
CC0 is pretty much a way to formalize public domain, so yeah, it's probably better.

**Comment by Lokathor** [comment]
Yeah. And, for those who aren't aware: not all jurisdictions actually recognize the concept of public domain, so CC0 (which has a fallback clause for such jurisdictions) is better than a simple public domain statement.

**Comment by LunarLambda** [comment]
> Yeah. And, for those who aren't aware: not all jurisdictions actually recognize the concept of public domain, so CC0 (which has a fallback clause for such jurisdictions) is better than a simple public domain statement.

I didn't know about this, that's good to know!

**Comment by avivace** [comment]
Great. Let's go with CC0.
