### ISSUE TITLE
github repo settings

### ISSUE THREAD

**Issue by Lokathor** [gbdev/gbadoc#5]
We should disable the Wiki tab. Content shouldn't get into the repo wiki, it should be going into the repo files which are published to github pages. Having the wiki enabled can give people the wrong idea.

We should also consider enabling the Discussions tab. We have the discord, but that's only good for short term discussions. For longer term questions, it's nice to have a place to post about something and people potentially can see it days or weeks from now.

**Comment by quentin-dev** [comment]
> For longer term questions, it's nice to have a place to post about something and people potentially can see it days or weeks from now.

How does this differ from opening an issue / RFC to discuss it?

**Comment by LunarLambda** [comment]
I'd say RFCs are for discussing a very particular issue with the goal of finding a definite answer, and we were thinking of only keeping RFCs open for around a week generally

Discussions are much less restrictive in what can be brought up and when

**Comment by avivace** [comment]
> We should disable the Wiki tab. Content shouldn't get into the repo wiki, it should be going into the repo files which are published to github pages. Having the wiki enabled can give people the wrong idea.
> 
> We should also consider enabling the Discussions tab. We have the discord, but that's only good for short term discussions. For longer term questions, it's nice to have a place to post about something and people potentially can see it days or weeks from now.

I'd keep the Wiki tab for some technical documentation (e.g. how to deploy) or some general rules (e.g. rules on units and acronyms) on how to write for gbadoc. Everything that needs fast/frequent iterations could go in there before getting committed in the main repository (so we don't fill the git history). Take a look at [Pan Docs Wiki](https://github.com/gbdev/pandocs/wiki), we do something similar over there

**Comment by Lokathor** [comment]
I think that's important to write down, but it should still be in the repository content itself.

in terms of history, we can always do squash merges when finalizing a PR.

**Comment by avivace** [comment]
> I think that's important to write down, but it should still be in the repository content itself.
> 
> in terms of history, we can always do squash merges when finalizing a PR.

I agree on this. I disabled the Wiki tab and enabled Discussions
